# Generated by Django 5.0 on 2023-12-19 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TutorApp', '0002_usersignup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlogin',
            old_name='username',
            new_name='useremail',
        ),
    ]
