# Generated by Django 4.2.2 on 2024-02-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TutorApp', '0005_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='uploaded_at',
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(max_length=30000, upload_to='images/'),
        ),
    ]
