# Generated by Django 4.2.2 on 2024-02-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TutorApp', '0007_alter_image_image_userstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatus',
            name='beginner',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='index',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='level',
            field=models.IntegerField(),
        ),
    ]
