# Generated by Django 4.2.2 on 2024-02-23 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TutorApp', '0008_alter_userstatus_beginner_alter_userstatus_index_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poseName', models.CharField(max_length=40)),
                ('index_no', models.IntegerField()),
                ('level', models.IntegerField()),
                ('img', models.ImageField(max_length=30000, upload_to='Poseimages/')),
                ('description', models.CharField(max_length=500)),
                ('lock', models.IntegerField()),
                ('pose_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TutorApp.usersignup')),
            ],
        ),
    ]
