# Generated by Django 4.2.2 on 2024-02-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TutorApp', '0009_userpose'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userbegupdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beg', models.IntegerField()),
                ('email', models.CharField(max_length=30)),
            ],
        ),
    ]
