# Generated by Django 4.2.2 on 2024-02-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TutorApp', '0010_userbegupdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstatus',
            name='id',
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='mail_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
