# Generated by Django 4.2.2 on 2024-02-25 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TutorApp', '0011_remove_userstatus_id_alter_userstatus_mail_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbegupdate',
            old_name='beg',
            new_name='begin',
        ),
    ]
