# Generated by Django 4.2.2 on 2024-02-25 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TutorApp', '0012_rename_beg_userbegupdate_begin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbegupdate',
            old_name='begin',
            new_name='update',
        ),
    ]
