# Generated by Django 4.2.2 on 2024-02-27 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TutorApp', '0015_rename_image_imagestore'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempImagestore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=30000, upload_to='tempimages/')),
            ],
        ),
    ]
