# Generated by Django 4.2.2 on 2024-02-27 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TutorApp', '0016_tempimagestore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpose',
            name='lock',
        ),
        migrations.RemoveField(
            model_name='userpose',
            name='pose_id',
        ),
    ]
