# Generated by Django 4.2.2 on 2024-02-27 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TutorApp', '0017_remove_userpose_lock_remove_userpose_pose_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpose',
            name='description',
            field=models.CharField(max_length=5000),
        ),
    ]
